eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka

#spring:
#  application:
#    name: eureka-3
server:
  port: 8764
other:
  eureka:
    host: 127.0.0.1
    port: 8888
tom:
  word: "abc"
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
#---
#spring:
#  profiles: eureka-1
#  application:
#    name: eureka-1
#
#server:
#  port: 8761
#
#eureka:
#  instance:
#    hostname: localhost
#
#other:
#  eureka:
#    host: 127.0.0.1
#    port: 8762
#
#---
#spring:
#  profiles: eureka-2
#  application:
#    name: eureka-2
#
#server:
#  port: 8762
#
#eureka:
#  instance:
#    hostname: localhost
#
#other:
#  eureka:
#    host: 127.0.0.1
#    port: 8761